name: DocuVault CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/docu-2 pytest

  build:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pycryptodome schedule requests
          if (Test-Path .github\workflows\requirements.txt) {
            pip install -r .github\workflows\requirements.txt
          }
      - name: Check directory structure
        run: |
          Get-ChildItem -Recurse -File | Where-Object {$_.Name -like "*.py"} | Select-Object FullName
      - name: Build with PyInstaller
        run: |
          cd docu-2
          pyinstaller --onefile main.py
      - name: Check dist directory
        run: |
          Get-ChildItem -Path docu-2\dist -Recurse
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docuvault-executable
          path: docu-2/dist/
          retention-days: 5

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docuvault-executable
          path: dist/
      - name: List downloaded files
        run: |
          ls -la dist/
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.run_number }}
          name: DocuVault Release v${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
