name: DocuVault CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Explicitly define permissions
permissions:
  contents: write  # Required for creating releases

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          flake8 . --exclude=./classifier_models --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Test with pytest
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/src pytest --ignore=./classifier_models

  build:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
            .github/workflows/requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pycryptodome schedule requests
          if (Test-Path .github\workflows\requirements.txt) {
            pip install -r .github\workflows\requirements.txt
          }
      
      - name: Cache PyInstaller build
        uses: actions/cache@v3
        with:
          path: |
            src/build
            src/__pycache__
          key: ${{ runner.os }}-pyinstaller-${{ hashFiles('src/**/*.py') }}
      
      - name: Build with PyInstaller
        run: |
          cd src
          pyinstaller --onefile main.py
      
      - name: Check dist directory
        run: |
          Get-ChildItem -Path src\dist -Recurse
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docuvault-executable
          path: src/dist/
          retention-days: 5

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Job-level permissions (optional, already set at workflow level)
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docuvault-executable
          path: dist/
      
      - name: List downloaded files
        run: |
          ls -la dist/
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.run_number }}
          name: DocuVault Release v${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
          # Using token, not both token and GITHUB_TOKEN env var
          token: ${{ secrets.GITHUB_TOKEN }}
        # Remove this env section as it's redundant with the token parameter
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
